import { DistrictsInterface } from "@/types";

const Districts: DistrictsInterface[] = [
  {
    id: 1,
    name: "Colombo",
    province: "Western",
    top: 0,
    left: 0,
    x: 2,
    y: 303,
  },
  {
    id: 2,
    name: "Gampaha",
    province: "Western",
    top: 0,
    left: 0,
    x: 2,
    y: 275,
  },
  {
    id: 3,
    name: "Kalutara",
    province: "Western",
    top: 0,
    left: 0,
    x: 25,
    y: 333,
  },
  {
    id: 4,
    name: "Kandy",
    province: "Central",
    top: 0,
    left: 0,
    x: 100,
    y: 255,
  },
  {
    id: 5,
    name: "Matale",
    province: "Central",
    top: 0,
    left: 0,
    x: 105,
    y: 228,
  },
  {
    id: 6,
    name: "Nuwara Eliya",
    province: "Central",
    top: 0,
    left: 0,
    x: 100,
    y: 285,
  },
  {
    id: 7,
    name: "Galle",
    province: "Southern",
    top: 0,
    left: 0,
    x: 51,
    y: 370,
  },
  {
    id: 8,
    name: "Matara",
    province: "Southern",
    top: 0,
    left: 0,
    x: 80,
    y: 380,
  },
  {
    id: 9,
    name: "Hambantota",
    province: "Southern",
    top: 0,
    left: 0,
    x: 135,
    y: 375,
  },
  {
    id: 10,
    name: "Jaffna",
    province: "Northern",
    top: 0,
    left: 0,
    x: 40,
    y: 5,
  },
  {
    id: 11,
    name: "Mannar",
    province: "Northern",
    top: 0,
    left: 0,
    x: 35,
    y: 92,
  },
  {
    id: 12,
    name: "Vavuniya",
    province: "Northern",
    top: 0,
    left: 0,
    x: 65,
    y: 105,
  },
  {
    id: 13,
    name: "Mullaitivu",
    province: "Northern",
    top: 0,
    left: 0,
    x: 80,
    y: 60,
  },
  {
    id: 14,
    name: "Kilinochchi",
    province: "Northern",
    top: 0,
    left: 0,
    x: 20,
    y: 40,
  },
  {
    id: 15,
    name: "Trincomalee",
    province: "Eastern",
    top: 0,
    left: 0,
    x: 150,
    y: 140,
  },
  {
    id: 16,
    name: "Batticaloa",
    province: "Eastern",
    top: 0,
    left: 0,
    x: 180,
    y: 200,
  },
  {
    id: 17,
    name: "Ampara",
    province: "Eastern",
    top: 0,
    left: 0,
    x: 198,
    y: 270,
  },
  {
    id: 18,
    name: "Badulla",
    province: "Uva",
    top: 0,
    left: 0,
    x: 135,
    y: 290,
  },
  {
    id: 19,
    name: "Monaragala",
    province: "Uva",
    top: 0,
    left: 0,
    x: 155,
    y: 320,
  },
  {
    id: 20,
    name: "Ratnapura",
    province: "Sabaragamuwa",
    top: 0,
    left: 0,
    x: 80,
    y: 335,
  },
  {
    id: 21,
    name: "Kegalle",
    province: "Sabaragamuwa",
    top: 0,
    left: 0,
    x: 60,
    y: 270,
  },
  {
    id: 22,
    name: "Kurunegala",
    province: "North Western",
    top: 0,
    left: 0,
    x: 40,
    y: 230,
  },
  {
    id: 23,
    name: "Puttalam",
    province: "North Western",
    top: 0,
    left: 0,
    x: 1,
    y: 200,
  },
  {
    id: 24,
    name: "Anuradhapura",
    province: "North Central",
    top: 0,
    left: 0,
    x: 57,
    y: 150,
  },
  {
    id: 25,
    name: "Polonnaruwa",
    province: "North Central",
    top: 0,
    left: 0,
    x: 120,
    y: 180,
  },
];

export default Districts;
